#!/bin/bash

#remove alias from pat
#20191129 km4ack

CONF=$HOME/.wl2k/config.json
TEMP=$HOME/patmenu/tempdel.txt
TODAY=$(date +%Y%m%d)
WHO=$(whoami)

cp $CONF $CONF.$TODAY.bkup


jq .connect_aliases $HOME/.wl2k/config.json | sed '/^}/d' | sed '/^{/d' | sed 's/^ *//g' > $TEMP

clear;echo;echo;echo "Here is your current alias list"
echo
while read LINE
do
echo $LINE
done < $TEMP

echo;echo;read -p "Which call sign would you like to remove? " CALL
echo;echo "You have chosen to remove "$CALL
read -p "Are you sure? y/n " ANS
if [ $ANS == 'y' ] || [ $ANS == 'Y' ]
then
CALL=$(echo $CALL | tr '[:lower:]' '[:upper:]')
jq 'del(.connect_aliases.'$CALL')' $CONF > $TEMP
cp $TEMP $CONF
sudo killall pat
sudo systemctl start pat@$WHO
echo;echo "Alias list updated"
sleep 2
else
echo;echo "Nothing deleted"
sleep 2
fi

rm $TEMP
