#!/bin/bash
# Pat manage menu
#20191129 km4ack

PS3='Please enter your choice: '


MAINMENU () {
clear;echo;echo;echo
echo "Pat Menu by KM4ACK"
echo
options=("Pat Login" "Add Alias ARDOP" "Add Alias Packet" "Delete Alias" "Restore Pat Config" "Exit")
select opt in "${options[@]}"
do
    case $opt in
        "Pat Login")
            $HOME/patmenu/patlogin
	    MAINMENU
            ;;
        "Add Alias ARDOP")
	    $HOME/patmenu/alias-add
	    MAINMENU
            ;;
        "Add Alias Packet")
	    $HOME/patmenu/alias-add-packet
	    MAINMENU
            ;;
        "Delete Alias")
	    $HOME/patmenu/alias-del
	    MAINMENU
            ;;
        "Restore Pat Config")
	    $HOME/patmenu/restore-config
	    MAINMENU
            ;;
        "Exit")
            exit 0
            ;;
        *) echo "invalid option $REPLY";;
    esac
done
}

MAINMENU
