#!/bin/bash

#script for logging in  operator for pat
#will mod ~/.wl2k/config.json file
#this will only change
#operator, callsign, grid, and http address

#km4ack 20190404
#last edit 20191116

FIG=$HOME/.wl2k/config.json

#HTTP port number
#taken from config file
PORT=$(cat $HOME/patmenu/config | grep '^PORT' | sed 's/PORT=//')


QUESTIONS () {
clear
echo
echo
echo
echo "What is your callsign"
echo "or 'exit' to quit"
read CALLSIGN
if [ -z "$CALLSIGN" ]
then 
QUESTIONS
elif [ $CALLSIGN == 'exit' ]
then exit
fi
echo "What is your winlink password?"
read PASS
echo "What is your grid square?"
read GRID
echo
echo
echo
echo "Your callsign is:$CALLSIGN"
echo "Your winlink password is:$PASS"
echo "Your grid is:$GRID"
echo
echo "Is this correct? y or n"
read ANSWER
if [ $ANSWER == 'y' ]
then
#set callsign
sed -i "s/\"mycall\": \".*\",/\"mycall\": \"$CALLSIGN\",/" $FIG
#set password
sed -i "s/\"secure_login_password\": \".*\",/\"secure_login_password\": \"$PASS\",/" $FIG
#set locator
sed -i "s/\"locator\": \".*\",/\"locator\": \"$GRID\",/" $FIG
#Change localhost to 0.0.0.0
sed -i "s/\"http_addr\": \".*\",/\"http_addr\": \"0.0.0.0:$PORT\",/" $FIG
echo "Config file has been updated"
echo "Pat is being restarted to aquire new credentials"
sleep 2
else
QUESTIONS
fi
}

QUESTIONS

#stop pat so we can grab new login
sudo killall pat
#get user name
WHO=$(whoami)
#need to restart pat to enable new login
sudo systemctl start pat@$WHO

