#!/bin/bash
# Pat menu system
#20191115 km4ack

PS3='Please enter your choice: '
source $HOME/patmenu/config
if [ $MYCALLSIGN = "N0CALL" ]
then
echo "Please see the config file before running Pat Menu"
echo "The config file is found in the ~/patmenu directory"
echo "See this video for more information https://youtu.be/unal5dCKGXk"
sleep 10
exit 0
fi

PATAUTO () {
	
	clear;echo;echo	
	echo "Which band would you like to use?"
	echo "20, 30, 40, or 80"
	read BAND
	if [ -z $BAND ]
	then
	echo "band cannot be blank"
	sleep 2
	PATAUTO
	fi
	if [ $BAND = "20" ] || [ $BAND = "30" ] || [ $BAND = "40" ] || [ $BAND = "80" ]
	then
	echo
	else
	echo "Only 20,30,40, or 80 are available"
	echo "Please try again"
	sleep 2
	PATAUTO
	fi
	echo "What is the max distance you wish to try?"
	read MAX
	if [ -z $MAX ]
	then 
	echo "max distance cannot be blank"
	sleep 2
	PATAUTO
	fi
	echo "What is the minimum distance you wish to try?"
	read MIN
	if [ $MIN -gt $MAX ]
	then
	echo "Minimum distance can't be greater than maximum distance"
	echo "Please try again"
	sleep 2
	PATAUTO
	fi
	echo "You have chosen to use "$BAND"M with a minimum distance of "$MIN"km"
	echo "and a maximum distance of "$MAX"km"
	read -p "Is this correct? y/n/exit :" ANS
	case $ANS in  
	  y|Y) echo "Please standby"
			$HOME/patmenu/autopat $MAX $BAND $MIN 
			MAINMENU
			;; 
	  n|N) PATAUTO 
			;; 
	  "exit") MAINMENU
			;;
	  *) echo "Invalid option. Try again"
	     sleep 2 
	     PATAUTO
			;; 
	esac
}

#catalog function
CATALOG () {
	clear;echo;echo
	$HOME/patmenu/catalog
	MAINMENU
}

#find ardop function
FINDARDOP () {
	clear;echo;echo
	$HOME/patmenu/findardop
	MAINMENU
}

MAINMENU () {
clear;echo;echo;echo
echo "Pat Menu by KM4ACK"
echo
options=("Manage Pat" "Start ARDOP" "Start Packet" "Find Ardop" "Pat Auto Connect" "Pat Catalog" "Stop Modems" "Manage Pat Menu" "Exit")
select opt in "${options[@]}"
do
    case $opt in
        "Manage Pat")
            $HOME/patmenu/pat-manage
	    MAINMENU
            ;;
        "Start ARDOP")
	    $HOME/patmenu/start-pat-ardop
	    MAINMENU
            ;;
        "Start Packet")
            $HOME/patmenu/start-pat2m
	    MAINMENU
            ;;
       "Find Ardop")
            FINDARDOP
            ;;
       "Pat Auto Connect")
	    PATAUTO
            ;;
       "Pat Catalog")
            CATALOG
            ;;
       "Stop Modems")
            $HOME/patmenu/stop-modems
	    MAINMENU
            ;;
	"Manage Pat Menu")
            $HOME/patmenu/menu-manage
	    MAINMENU
            ;;
        "Exit")
            exit 0
            ;;
        *) echo "invalid option $REPLY";;
    esac
done
}

MAINMENU
