#!/bin/bash

#Script to install and setup Pat
#and the km4ack pat menu system
#km4ack 20190404

clear
echo;echo;echo;

#check if patmenu already installed
if [ -f $HOME/ardop/patmenu ]
then
echo "It looks like you have a version of Pat Menu"
echo "already installed. If you continue, the current"
echo "version will be deleted and the latest version"
echo "will be installed. Continue? y/n"
read REMOVEOLD
        if [ $REMOVEOLD == "y" ]
        then
        #remove old menu files so we get latest revisions
	#don't remove entire dir in case user has added files
        rm $HOME/ardop/start-pat
        rm $HOME/ardop/stop-pat
        rm $HOME/ardop/findardop
        rm $HOME/ardop/getardoplist
        rm $HOME/ardop/grid-map.pdf
        rm $HOME/ardop/patmenu
        rm $HOME/ardop/patlogin
        rm $HOME/ardop/worldgridmap.pdf
        rm $HOME/ardop/uninstall
        else
        exit
        fi
fi


PAT=$(dpkg --get-selections | grep -w "pat")
#check if pat is install & offer to install if needed
if [ -z "$PAT" ]
then
echo "Pat is not installed"
echo "Would you like to install it now? y/n"
read PATANSWER
	if [ $PATANSWER == 'y' ]
	then
	cd $HOME/Downloads
	wget https://github.com/la5nta/pat/releases/download/v0.6.1/pat_0.6.1_linux_armhf.deb
	sudo dpkg -i pat_0.6.1_linux_armhf.deb
	else
	echo "No point to continue without pat installed"
	exit
	fi
else
echo "Pat was found on this system"
fi

#get piardopc and piardop_gui
mkdir -p $HOME/ardop/
#check if ardop & ardop_gui already exist in ardop dir
if [ ! -f $HOME/ardop/piardopc ]; then
    echo "piardopc not found in directory"
    echo "Downloading now, please standby"
    cd $HOME/ardop/
    wget http://www.cantab.net/users/john.wiseman/Downloads/Beta/piardopc
    sudo chmod +x piardopc
else
echo "Piardopc was found on this system"
fi

if [ ! -f $HOME/ardop/piARDOP_GUI ]; then
    echo "piARDOP_GUI not found in directory"
    echo "Downloading now, please standby"
    cd $HOME/ardop/
    wget https://www.cantab.net/users/john.wiseman/Downloads/Beta/piARDOP_GUI
    sudo chmod +x piARDOP_GUI
else
echo "piARDOP_GUI was found on this system"
fi

#get km4ack scripts & menu system

#make dir if doesn't exist
mkdir -p $HOME/Downloads
cd $HOME/Downloads
#clone pat menu from github
git clone https://github.com/km4ack/Pat-Menu.git
cd Pat-Menu
#make files exec
sudo chmod +x start-pat stop-pat patmenu findardop getardoplist patlogin patsetup uninstall
#make dir if doesn't exist
mkdir -p $HOME/ardop
#move files to where they go
cp $HOME/Downloads/Pat-Menu/* $HOME/ardop/
#remove download dir
rm -rf $HOME/Downloads/Pat-Menu

#Set Callsign,Winlink Password & locator in Pat Config File
FIG=$HOME/.wl2k/config.json

#HTTP port number
#default is 8080
PORT=8080


QUESTIONS () {
clear
echo;echo;echo
echo "Next 3 questions pertain to your Winlink Credentials"
echo
echo "What is your callsign"
read CALLSIGN
if [ -z "$CALLSIGN" ]
then 
QUESTIONS
fi
echo "What is your winlink password?"
read PASS
echo "What is your grid square?"
read GRID
echo
echo
echo
echo "Your callsign is:$CALLSIGN"
echo "Your winlink password is:$PASS"
echo "Your grid is:$GRID"
echo
echo "Is this correct? y or n"
read ANSWER
if [ $ANSWER == 'y' ]
then
#set callsign
sed -i "s/\"mycall\": \".*\",/\"mycall\": \"$CALLSIGN\",/" $FIG
#set password
sed -i "s/\"secure_login_password\": \".*\",/\"secure_login_password\": \"$PASS\",/" $FIG
#set locator
sed -i "s/\"locator\": \".*\",/\"locator\": \"$GRID\",/" $FIG
#Change localhost to 0.0.0.0
sed -i "s/\"http_addr\": \".*\",/\"http_addr\": \"0.0.0.0:$PORT\",/" $FIG
echo "Config file has been updated"
fi
}

QUESTIONS

if [ $ANSWER == 'n' ]
then
QUESTIONS
fi

#check to see if ardop list exist. get if needed.
if [ -f $HOME/Documents/ardop-list/ardoplist.txt ]
then
    echo "ARDOP list exist. No need to download"
else
#run initial getardoplist
echo "Please wait while the latest"
echo "Gateway list is downloaded"
$HOME/ardop/getardoplist
fi



#set getardoplist in cron
crontab -l > $HOME/ardop/crontemp.txt
echo "00 12 * * * $HOME/ardop/getardoplist" > $HOME/ardop/crontemp.txt
#line below commented out during testing
#crontab $HOME/ardop/crontemp.txt
rm $HOME/ardop/crontemp.txt

#check to see if evince is installed
EV=$(dpkg --get-selections | grep -w "evince")
if [ -z "$EV" ]
then
#install evince pdf reader
sudo apt-get install -y evince
fi

#create config file for ARDOP_GUI
if [ -f $HOME/.config/G8BPQ/ARDOP_GUI.conf ]
then
    echo "ARDOP_GUI Config exists"
else
mkdir -p $HOME/.config/G8BPQ
echo "[General]" >> $HOME/.config/G8BPQ/ARDOP_GUI.conf
echo "Host=local" >> $HOME/.config/G8BPQ/ARDOP_GUI.conf
echo "Port=8515" >> $HOME/.config/G8BPQ/ARDOP_GUI.conf
fi

#give user option to change to world map
echo;echo;echo;
echo "Would you like to use a world grid square map"
echo "instead of the default USA grid square map? y/n"
read MAP
if [ $MAP == "y" ]
then
sed -i s'/grid-map.pdf/worldgridmap.pdf/' $HOME/ardop/findardop
fi

rm $HOME/Downloads/patsetup

#create symlink for patmenu
sudo ln -sf $HOME/ardop/patmenu /usr/local/bin/patmenu

echo;echo;echo;echo
echo "#############################################################"
echo "#                                                           #"
echo "#    Start the menu with 'patmenu' from the command line    #"
echo "#                                                           #"
echo "#############################################################"
