#!/bin/bash

#script to setup patmenu system after downloaded

#20191117

cd $HOME/patmenu

chmod +x autopat catalog findardop getardoplist patlogin patmenu-new start-pat2m start-pat-ardop stop-modems uninstall update


#check if evince is installed
EVINCE=$(dpkg --get-selections | grep -w "evince")
if [ -z "$EVINCE" ]
then
sudo apt-get install -y evince
else
echo "evince is already installed"
fi

#check to see if ardop list exist. get if needed.
if [ -f $HOME/patmenu/ardop-list/ardoplist.txt ]
then
    echo "ARDOP list exist. No need to download"
else
#run initial getardoplist
echo "Please wait while the latest"
echo "Gateway list is downloaded"
$HOME/patmenu/getardoplist
fi

#create symlink on desktop
ln -s $HOME/patmenu/patmenu-new $HOME/Desktop/Pat-Menu

#remove a few files
rm $HOME/patmenu/readme.md
rm $HOME/patmenu/patsetup

echo "#########################################"
echo "#      Please see config file before.   #"
echo "#      running Pat Menu. There is a     #"
echo "#      new icon on the desktop to start #"
echo "#      the new menu system. Double      #"
echo "#      click the icon and choose        #"
echo "#      "execute in terminal"            #"
echo "#########################################"
