#!/bin/bash

#start ardop modem

#20191118 km4ack

source $HOME/patmenu/config

echo "stand by while the modem starts"

SETRIG () {

#Set USB Mode
RIGUSB=$RIG" M $MODEHF 0"

#check rig is in USB
MODE=$($RIG m | grep $MODEHF)

sleep 1

	MODECHECK() {
	#check rig is in correct mode
	MODE=$($RIG m | grep $MODEHF)
	}

sleep 1

	if [ -z $MODE ]
	then
	$RIGUSB
	MODECHECK
	fi

}

#see if rig control is used
if [ $RIGCONTROL == 'yes' ]
then 
SETRIG
fi

#start modem
$ARDOP
