#!/bin/bash

#start ardop modem

#20191118 km4ack

source $HOME/patmenu/config

if [ $AMRRON = "no" ] > /dev/null 2>&1
then
#check if direwolf is running
PIDDW=$(pidof direwolf)
if [ -z "$PIDDW" ]
then
echo
else
echo;echo;
echo "It looks like the 2M/440 Modem is running"
echo "Stop all modems and try again."
sleep 5
exit 0
fi

fi

clear;echo;echo;echo
echo "stand by while the modem starts"

SETRIG () {

#Set USB Mode
RIGUSB=$RIG" M $MODEHF 0"

#check rig is in USB
MODE=$($RIG m | grep $MODEHF)

sleep 1

	MODECHECK() {
	#check rig is in correct mode
	MODE=$($RIG m | grep $MODEHF)
	}

sleep 1

	if [ -z $MODE ]
	then
	$RIGUSB
	MODECHECK
	fi

}

#see if rig control is used
if [ $RIGCONTROL == 'yes' ]
then
PIDCTL=$(pidof rigctld)
WHO=$(whoami)
	if [ -z "$PIDCTL" ]
	then	
	CONTROL=$(cat $HOME/patmenu/config | grep '^RIG="' | sed 's/RIG="//' | sed 's/"//' | sed 's/rigctl/rigctld/')
	$CONTROL &
	sudo systemctl restart pat@$WHO
	fi
SETRIG
fi

#Start ARDOP_GUI
$ARDOPGUI </dev/null &>/dev/null &

#start modem
$ARDOP </dev/null &>/dev/null &
sleep 2


#verify that piardopc is running
PIDPIC=$(pidof piardopc)
if [ -z "$PIDPIC" ]
then
echo;echo
echo "The modem didn't start"
sleep 3
else
echo;echo
echo "The modem has started"
sleep 3
fi

#open pat inbox in browser
export DISPLAY=:0 && chromium-browser --app=http://127.0.0.1:$PORT > /dev/null 2>&1 &











