#!/bin/bash

#this script will start piardopc,piARDOP_GUI, & pat
#server.
#20181216 km4ack
#20190404 last edit

#####################################################
#-----------------CHANGE NOTES----------------------#
#####################################################

#20181216 original script written
#20190226 added open chrome browser to display inbox
#20190404 added variable for PORT
#20190408 comment out open chrome and remove & after pat http
####################################################
#-----------------END NOTES------------------------#
####################################################

#set sound card number
#User may need to change this is sound card is different
#find with 'arecord -l' at commnad line
#more info - https://youtu.be/w0dy42TLd_o
CARD=1,0

#path to ardop
APATH=$HOME/ardop

#stop programs that might interfere with pat running
sudo killall piardopc
sudo killall pat
sudo killall js8call
sleep 5

#start piardopc
$APATH/./piardopc 8515 plughw:$CARD plughw:$CARD  &

#start ardop-gui
export DISPLAY=:0 && $APATH/piARDOP_GUI &

sleep 2

#start pat
pat http

sleep 1

#get port number from config.json
PORT=$(grep -w "http_addr" $HOME/.wl2k/config.json | sed 's/.*: //;s/.*://;s/",//')

#open inbox in chrome browser window
export DISPLAY=:0 && chromium-browser http://127.0.0.1:$PORT
