#!/bin/bash

#script to start Pat for 2m packet work
#20191116 km4ack

clear

source $HOME/patmenu/config

echo;echo;
echo "Please standby"
echo "The Pat Menu will open in a new window in just a moment"
echo;echo
sudo killall direwolf kissattach > /dev/null 2>&1
sleep 1

#Set Mode
RIGFM=$RIG" M $MODE2M 0"

#set the long date
TODAY=$(date)

#set path to my log
MYLOG=$HOME/Documents/mylog.txt

SETRIG () {

#set radio frequency & mode
$RIGFM

sleep 1

#check rig is in correct mode
MODE=$($RIG m | grep $MODE2M)

sleep 1

	MODECHECK() {
	#check rig is in correct mode
	MODE=$($RIG m | grep $MODE2M)
	}

sleep 1

	if [ -z $MODE ]
	then
	$RIGFM
	MODECHECK
	fi
}


#see if rig control is used
if [ $RIGCONTROL == 'yes' ]
then 
PIDCTL=$(pidof rigctld)
WHO=$(whoami)
	if [ -z "$PIDCTL" ]
	then	
	CONTROL=$(cat $HOME/patmenu/config | grep '^RIG="' | sed 's/RIG="//' | sed 's/"//' | sed 's/rigctl/rigctld/')
	$CONTROL &
	sudo systemctl restart pat@$WHO
SETRIG
fi

#start direwolf
/usr/local/bin/$DIREWOLF &

sleep 5

#start kissattach
sudo /usr/sbin/kissattach /tmp/kisstnc wl2k
sudo kissparms -c 1 -p wl2k
echo;echo;echo;
echo "#################################################"
echo "#    Leave this window open while you make      #"
echo "#    your packet connection.                    #"
echo "#    Closing this window will stop direwolf     #"
echo "#    and your packet connection will not work   #"
echo "#################################################"

