#!/bin/bash

#uninstall script for pat menu 
#km4ack 20191120

clear
echo;echo;echo
echo "This will uninstall all files for the Pat Menu"
echo "System. This WILL NOT uninstall piardopc or"
echo "piARDOP_GUI since both of these are used"
echo "with Pat Winlink. This will also NOT uninstall"
echo "Pat winlink"
echo
echo "Continue? y/n"
read ANSWER

if [ $ANSWER == "y" ]
then
cd $HOME
rm -rf $HOME/patmenu
rm $HOME/Desktop/Pat-Menu
else
exit
fi

echo;echo;echo
echo "Uninstall complete"
echo "Thanks for trying the Pat Menu System"
echo "73, KM4ACK"
