#!/bin/bash

#20191117 km4ack

#script to update pat-menu system if needed

#get the release file from github
cd $HOME/patmenu/
wget -O $HOME/patmenu/latest https://raw.githubusercontent.com/km4ack/patmenu/master/release

#get date of latest release
LATEST=$(cat $HOME/patmenu/latest | grep '^release' | sed 's/release=//')


#get current release
CURRENT=$(cat $HOME/patmenu/release | grep '^release' | sed 's/release=//')


#compare versions

if (( $(echo "$LATEST $CURRENT" | awk '{print ($1 > $2)}') ))
then
clear
echo "Pat-Menu needs to be updated"
echo
echo "Here's the change log"
cat latest | head -n 17 | tail -n +8
echo;echo
echo "Current installed version is "$CURRENT
echo
echo "Would you like to update now? y/n"
read ANSWER
  if [ $ANSWER == 'y' ]
  then
  mkdir -p $HOME/Downloads
  cd $HOME/Downloads
  cp $HOME/patmenu/config $HOME/Downloads/
  git clone https://github.com/km4ack/patmenu.git
  cp $HOME/Downloads/patmenu/* $HOME/patmenu/
  mv $HOME/Downloads/config $HOME/patmenu/
  rm -rf $HOME/Downloads/patmenu
  chmod +x $HOME/patmenu/setup
  $HOME/patmenu/./setup
  fi
else
clear;echo;echo;echo;
echo "Latest version already installed"
sleep 2
fi

rm $HOME/patmenu/latest

