#!/bin/bash

#20191117

#script to update pat-menu system if needed

#set date
NOW=$(date +%Y%m%d)

#get the release file from github
cd $HOME/patmenu/
wget https://raw.githubusercontent.com/km4ack/Pat-Menu/master/release

#get date of latest release
LATEST=$(cat release | grep '^release' | sed 's/release=//')

#compare dates

if [ $NOW -lt $LATEST ]
then
clear
echo "Pat-Menu needs to be updated"
echo "Would you like to update now? y/n"
read ANSWER
  if [ $ANSWER == 'y' ]
  then
  mkdir -p $HOME/Downloads
  cd $HOME/Downloads
  git clone https://github.com/km4ack/patmenu.git
  cp $HOME/Downloads/patmenu/* $HOME/patmenu/
  rm -rf $HOME/Downloads/patmenu
  chmod +x $HOME/patmenu/setup
  $HOME/patmenu/./setup
  fi
else
echo "Latest version already installed"
fi

rm $HOME/patmenu/release

